### ISSUE TITLE
I got There was an error while trying to load the gem 'textris'. (Bundler::GemRequireError)

### ISSUE THREAD

**Issue by ryzalyusoff** [visualitypl/textris#7]
Hi,

I am trying to use textris on my rails app. But I got "There was an error while trying to load the gem 'textris'. (Bundler::GemRequireError)" error.

This is the full error:

```
Colins-MacBook-Pro:rentlord Ryzal$ rails s
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'textris'. (Bundler::GemRequireError)
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from /Users/Ryzal/Desktop/Sites/rentlord/config/application.rb:8:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:78:in `block in server'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Any help? Thanks!

**Comment by nowakov** [comment]
Hey @ryzalyusoff do you still need help with that? what's your ruby & rails version?

**Comment by josh22r** [comment]
Hi, 
I am receiving this error also in a Windows x64 environment.  

rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'textris'.
Gem Load Error is: uninitialized constant FILE
Backtrace for gem load error is:
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libxml-ruby-3.0.0-x64-mingw32/lib/libxml.rb:2:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twilio-ruby-5.4.5/lib/twilio-ruby.rb:3:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/textris-0.4.4/lib/textris.rb:7:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `block (2 levels) in require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `each'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `block in require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `each'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/bundler.rb:114:in `require'

**Comment by Marahin** [comment]
Is this still an issue for any of the Windows users? We haven't seen much of activity here, so considering to close the issue.

**Comment by Marahin** [comment]
Since there is no activity I'm closing this issue.
